# See: https://dart.dev/tools/pub/pubspec
name: model_viewer
version: 0.9.0-nullsafety.0
description: >-
  A Flutter widget for rendering interactive 3D models in the glTF and GLB
  formats.
publish_to: none #TODO: delete line after merge in pub
homepage: https://github.com/drydart/model_viewer.dart
repository: https://github.com/drydart/model_viewer.dart
issue_tracker: https://github.com/drydart/model_viewer.dart/issues
documentation:
dependencies:
  flutter:
    sdk: flutter
  flutter_android:
    git:
      url: git://github.com/Mozyra/flutter_android.git
      ref: null-safety-support
  webview_flutter: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
dependency_overrides:
environment:
  sdk: '>=2.12.0 <3.0.0'
flutter:
  assets:
    - etc/assets/template.html
    - etc/assets/model-viewer.js
